# Secret. Keep these values safe.
server:
  id: ""
  key: ""

# Add any custom events detected via console message here.
# Click "Create Custom Event" in the `Custom Events` section of our dashboard
# to automatically generate new event configurations.
custom-events:
  # [EXAMPLE] This will generate an event when a player issues a command
  - name: "command_executed"
    type: "console"
    console-pattern: "(.+) issued server command: (.*)"
    player-field: 1 # username in the message
    metadata:
      - command:
          key: "command"
          field: 2

exempt:
  players: []

# Playercount multiplier - multiply the playercount by this value.
# This is useful to "undo" spoofer plugins that fake the playercount.
# For example, if your spoofer multiplies the playercount by 10, you can set this to 0.1.
playercount-multiplier: 1.0

# Playercount subtract - subtract this value from the playercount.
# This is useful to "undo" spoofer plugins that fake the playercount.
# For example, if your spoofer adds 10 to the playercount, you can set this to 10.
# ORDER OF OPERATIONS: playercount-multiplier * playercount - playercount-subtract
playercount-subtract: 0

# Log level - default, debug, or silent
# Debug: more verbose logging
# Silent: Avoids most console logs, only critical errors or warnings
log-level: default

# Disable console event listener - set to true to disable console event tracking completely
disable-console-listener: false

# Don't change this value
config-version: 3
