name: MCMetrics
version: "${version}"
main: net.mcmetrics.plugin.MCMetricsSpigotPlugin
api-version: "1.13"
folia-supported: true
commands:
  mcmetrics:
    description: MCMetrics admin commands
    usage: /<command> <payment|customevent> ...
    permission: mcmetrics.admin
