name: Build and Upload to R2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle

      - uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

    #   - name: Upload Bukkit JAR
    #     uses: cloudflare/wrangler-action@2.0.0
    #     with:
    #       apiToken: ${{ secrets.CF_API_TOKEN }}
    #       accountId: ${{ secrets.CF_ACCOUNT_ID }}
    #       command: r2 object put your-bucket-name/bukkit-${{ github.sha }}.jar ./bukkit/build/libs/bukkit-*.jar

    #   - name: Upload BungeeCord JAR
    #     uses: cloudflare/wrangler-action@2.0.0
    #     with:
    #       apiToken: ${{ secrets.CF_API_TOKEN }}
    #       accountId: ${{ secrets.CF_ACCOUNT_ID }}
    #       command: r2 object put your-bucket-name/bungeecord-${{ github.sha }}.jar ./bungeecord/build/libs/bungeecord-*.jar

    #   - name: Upload Velocity JAR
    #     uses: cloudflare/wrangler-action@2.0.0
    #     with:
    #       apiToken: ${{ secrets.CF_API_TOKEN }}
    #       accountId: ${{ secrets.CF_ACCOUNT_ID }}
    #       command: r2 object put your-bucket-name/velocity-${{ github.sha }}.jar ./velocity/build/libs/velocity-*.jar
