name: Build and Upload to GitHub Packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Get version
        id: get_version
        run: echo "VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Upload Bukkit JAR
        uses: actions/upload-artifact@v3
        with:
          name: bukkit-mcmetrics-${{ steps.get_version.outputs.VERSION }}
          path: bukkit/build/libs/bukkit-mcmetrics-${{ steps.get_version.outputs.VERSION }}.jar

      - name: Upload BungeeCord JAR
        uses: actions/upload-artifact@v3
        with:
          name: bungeecord-mcmetrics-${{ steps.get_version.outputs.VERSION }}
          path: bungeecord/build/libs/bungeecord-mcmetrics-${{ steps.get_version.outputs.VERSION }}.jar

      - name: Upload Velocity JAR
        uses: actions/upload-artifact@v3
        with:
          name: velocity-mcmetrics-${{ steps.get_version.outputs.VERSION }}
          path: velocity/build/libs/velocity-mcmetrics-${{ steps.get_version.outputs.VERSION }}.jar
